version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    schedule:
      interval: "daily"

 # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    schedule:
      interval: "weekly"

  # Maintain dependencies for npm
  - package-ecosystem: "gomod"
    directory: "/"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Composer
  - package-ecosystem: "docker"
    directory: "/"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    schedule:
      interval: "weekly"